name: Auto Release

on:
  push:
    branches:
      - main

env:
  DEFAULT_PYTHON: "3.12"

permissions:
  contents: write

jobs:
  build:
    name: Build and upload release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Install build tool
        run: python -m pip install --upgrade pip build

      - name: Determine version
        id: version
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "v0.1.0")
          echo "VERSION=$TAG" >> $GITHUB_ENV
          echo "Version to release: $TAG"

      - name: Build distributions
        run: python -m build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          files: dist/*
