matrix:
- name: en
  hidden: true
  aspell:
    lang: en
    ignore-case: true
  dictionary:
    wordlists:
    - admin_utils/spellcheck/.wordlist_en.txt
    encoding: utf-8
  pipeline:
  - resplendent.filters.restructuredtext:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - :matches(code, pre)
  sources:
  - 'docs/**/*[^_ru].rst'
  - 'final_project/*.rst'
  default_encoding: utf-8

- name: ru
  hidden: true
  aspell:
    lang: ru
    ignore-case: true
  dictionary:
    wordlists:
    - admin_utils/spellcheck/.wordlist.txt
    - admin_utils/spellcheck/.wordlist_en.txt
    encoding: utf-8
  pipeline:
  - resplendent.filters.restructuredtext:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - :matches(code, pre)
  sources:
  - 'lab*/*.rst'
  - 'final_project/*.rst'
  - '*.rst'
  - 'docs/**/*_ru.rst'
  default_encoding: utf-8

- name: docstrings
  hidden: true
  aspell:
    lang: en
    ignore-case: true
  dictionary:
    wordlists:
    - admin_utils/spellcheck/.wordlist_en.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.python:
      docstrings: true
      comments: false
  sources:
  - 'lab*/**/*.py'
  - 'lab*/*.py'
  - 'reference*/*.py'
  - 'config/**/*.py'
  - 'config/*.py'
  default_encoding: utf-8
