name: Auto Release

on:
  push:
    branches:
      - main

env:
  DEFAULT_PYTHON: "3.12"

permissions:
  contents: write

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Install build tool
        run: python -m pip install --upgrade pip build


      - name: Get current version
        id: current
        run: |
          VERSION=$(grep '^version' pyproject.toml | sed 's/.*"\(.*\)"/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get the latest tag
        id: latest_tag
        run: |
          TAG=$(git tag --sort=-v:refname | head -n 1)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare
        run: |
          CURRENT="v${{ steps.current.outputs.version }}"
          LATEST="${{ steps.latest_tag.outputs.tag }}"

          echo "Current version is ${CURRENT}, the latest release version is ${LATEST}."
          if [ "$CURRENT" != "$LATEST" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Build distributions
        run: python -m build

      - name: Create tag
        if: steps.compare.outputs.changed == 'true'
        run: |
          git tag v${{ steps.current.outputs.version }}
          git push origin v${{ steps.current.outputs.version }}

      - name: Create Release
        if: steps.compare.outputs.changed == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.current.outputs.version }}
          name: "Release ${{ steps.current.outputs.version }}"
          files: dist/*
